version: '3.7'

networks:
  default:
    driver: ${NETWORKS_DRIVER}

services:
  app:
    volumes:
      - ${DOCKER_VOLUME_CODES_ROOT_DIR}:/usr/src/app
    extra_hosts:
      - "host.docker.internal:host-gateway"